#!/bin/bash

# Description: Script downloading photos from camera and organizing
#              them into folders by exif timestamp (/YYYY/YYYY-MM-DD).
# Author:      Maciej 'mc' Suchecki

ext='JPG'                        # extension of files from camera
camera='Canon'                   # camera manufacturer (not important)
path='/home/mc/pic/'             # directory where photos should be placed

# checking if parent directory exist
if [ ! -d "$path" ]; then
  echo 'Error - parent directory does not exist, aborting!'
  exit 1
fi

# checking if current year subdirectory exist, if not create it
year=`date +"%Y"`
if [ ! -d "$path$year" ]; then
  echo "Year $year subdirectory doesn't exist - creating..."
  mkdir "$path$year"
fi

# checking if year subfolder was created and changing path
if [ ! -d "$path$year" ]; then
  echo "Error - directory $path$year not created!"
  exit 1
else
  path="$path$year/"
  echo "Photos will be copied to: $path"
fi

echo 'Detecting camera...'
gphoto2 --auto-detect | grep $camera
echo 'Downloading new photos...'
gphoto2 --get-all-files --new

echo 'Moving files...'
for photo in `ls *.$ext`; do

  dir=`exiv2 $photo | grep timestamp -a | cut -c 19- | cut -c -10 | sed 's/:/-/g'`

  if [ ! -d "$path$dir" ]; then
    echo "Creating directory $path$dir..."
    mkdir "$path$dir"
  fi

  if [ ! -d "$path$dir" ]; then
    echo "Error - directory $path$dir not created!"
    exit 1
  else
    echo "Moving $photo"
    mv $photo "$path$dir"
  fi

done

echo 'Done!'
exit 0
